import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/public/css/style.css"
import { GlobalProvider } from "@/lib/GlobalState";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LotoJs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className="dark">
      <body
        className={`relative flex items-center justify-center h-[100dvh] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalProvider>
          {children}
          <Toaster richColors />
        </GlobalProvider>
      </body>
    </html>
  );
}
