import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/public/css/style.css"
import { GlobalProvider } from "@/lib/GlobalState";
import { AuthProvider } from "@/lib/AuthContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LotoJs",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className="dark">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </head>
      <body
        className={`relative h-screen w-full ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ overflow: 'hidden' }}
      >
        <AuthProvider>
        <GlobalProvider>
            <div className="h-full w-full" style={{ overflow: 'hidden' }}>
          {children}
            </div>
          <Toaster richColors />
        </GlobalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
